#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 11 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
    using AntJob.Data;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
    using AntJob.Data.Entity;
    
    #line default
    #line hidden
    using AntJob.Web;
    
    #line 2 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Ant/Views/Job/_List_Data.cshtml")]
    public partial class _Areas_Ant_Views_Job__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<AntJob.Data.Entity.Job>>
    {
        public _Areas_Ant_Views_Job__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 12 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as List<FieldItem>;
    var fk = fact.Unique;
    var enableSelect = this.EnableSelect();

    var appid = page["appid"].ToInt();

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 24 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
             if (enableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 27 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 895), Tuple.Create("\"", 934)
            
            #line 28 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 902), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 902), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 987), Tuple.Create("\"", 1028)
            
            #line 29 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 994), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Name"))
            
            #line default
            #line hidden
, 994), false)
);

WriteLiteral(">名称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1081), Tuple.Create("\"", 1129)
            
            #line 30 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1088), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("DisplayName"))
            
            #line default
            #line hidden
, 1088), false)
);

WriteLiteral(">显示名</a></th>\r\n");

            
            #line 31 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 31 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
             if (appid == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1232), Tuple.Create("\"", 1276)
            
            #line 33 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1239), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("AppName"))
            
            #line default
            #line hidden
, 1239), false)
);

WriteLiteral(">应用</a></th>\r\n");

            
            #line 34 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1344), Tuple.Create("\"", 1386)
            
            #line 35 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1351), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Start"))
            
            #line default
            #line hidden
, 1351), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1387), Tuple.Create("\"", 1419)
            
            #line 35 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
         , Tuple.Create(Tuple.Create("", 1395), Tuple.Create<System.Object, System.Int32>(Job._.Start.Description
            
            #line default
            #line hidden
, 1395), false)
);

WriteLiteral(">开始时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1474), Tuple.Create("\"", 1514)
            
            #line 36 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1481), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("End"))
            
            #line default
            #line hidden
, 1481), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1515), Tuple.Create("\"", 1545)
            
            #line 36 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
       , Tuple.Create(Tuple.Create("", 1523), Tuple.Create<System.Object, System.Int32>(Job._.End.Description
            
            #line default
            #line hidden
, 1523), false)
);

WriteLiteral(">结束</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1598), Tuple.Create("\"", 1639)
            
            #line 37 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1605), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Step"))
            
            #line default
            #line hidden
, 1605), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1640), Tuple.Create("\"", 1671)
            
            #line 37 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
        , Tuple.Create(Tuple.Create("", 1648), Tuple.Create<System.Object, System.Int32>(Job._.Step.Description
            
            #line default
            #line hidden
, 1648), false)
);

WriteLiteral(">步进</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1724), Tuple.Create("\"", 1770)
            
            #line 38 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1731), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("BatchSize"))
            
            #line default
            #line hidden
, 1731), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1771), Tuple.Create("\"", 1807)
            
            #line 38 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
             , Tuple.Create(Tuple.Create("", 1779), Tuple.Create<System.Object, System.Int32>(Job._.BatchSize.Description
            
            #line default
            #line hidden
, 1779), false)
);

WriteLiteral(">批大小</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1861), Tuple.Create("\"", 1904)
            
            #line 39 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1868), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Offset"))
            
            #line default
            #line hidden
, 1868), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1905), Tuple.Create("\"", 1938)
            
            #line 39 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
          , Tuple.Create(Tuple.Create("", 1913), Tuple.Create<System.Object, System.Int32>(Job._.Offset.Description
            
            #line default
            #line hidden
, 1913), false)
);

WriteLiteral(">偏移</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1991), Tuple.Create("\"", 2035)
            
            #line 40 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1998), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("MaxTask"))
            
            #line default
            #line hidden
, 1998), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 2036), Tuple.Create("\"", 2070)
            
            #line 40 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
           , Tuple.Create(Tuple.Create("", 2044), Tuple.Create<System.Object, System.Int32>(Job._.MaxTask.Description
            
            #line default
            #line hidden
, 2044), false)
);

WriteLiteral(">并行</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2123), Tuple.Create("\"", 2165)
            
            #line 41 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2130), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Total"))
            
            #line default
            #line hidden
, 2130), false)
);

WriteLiteral(">总数</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2218), Tuple.Create("\"", 2262)
            
            #line 42 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2225), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Success"))
            
            #line default
            #line hidden
, 2225), false)
);

WriteLiteral(">成功</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2315), Tuple.Create("\"", 2357)
            
            #line 43 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2322), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Error"))
            
            #line default
            #line hidden
, 2322), false)
);

WriteLiteral(">错误</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2410), Tuple.Create("\"", 2452)
            
            #line 44 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2417), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Times"))
            
            #line default
            #line hidden
, 2417), false)
);

WriteLiteral(">次数</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2505), Tuple.Create("\"", 2547)
            
            #line 45 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2512), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Speed"))
            
            #line default
            #line hidden
, 2512), false)
);

WriteLiteral(">速度</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2600), Tuple.Create("\"", 2643)
            
            #line 46 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2607), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Enable"))
            
            #line default
            #line hidden
, 2607), false)
);

WriteLiteral(">启用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2696), Tuple.Create("\"", 2743)
            
            #line 47 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2703), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateTime"))
            
            #line default
            #line hidden
, 2703), false)
);

WriteLiteral(">更新时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">消息</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">任务</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">统计</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">错误</th>\r\n");

            
            #line 52 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 52 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 55 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 59 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 59 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
         foreach (var entity in Model)
        {
            var st = entity.Start.ToFullString("");
            if (entity.Start.Date == DateTime.Now.Date) { st = entity.Start.ToString("HH:mm:ss"); }
            if (entity.Mode == JobModes.Message) { st = "{0}/{1}".F(entity.Topic, entity.MessageCount); }

            var ut = entity.UpdateTime.ToFullString("");
            if (entity.UpdateTime.Date == DateTime.Now.Date) { ut = entity.UpdateTime.ToString("HH:mm:ss"); }

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 68 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 68 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                 if (enableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3795), Tuple.Create("\"", 3819)
            
            #line 70 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 3803), Tuple.Create<System.Object, System.Int32>(entity[fk.Name]
            
            #line default
            #line hidden
, 3803), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 71 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral(">");

            
            #line 72 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                                                 Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3958), Tuple.Create("\"", 3989)
, Tuple.Create(Tuple.Create("", 3965), Tuple.Create("JobTask?JobID=", 3965), true)
            
            #line 73 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3979), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 3979), false)
);

WriteLiteral(">");

            
            #line 73 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                                  Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 4033), Tuple.Create("\"", 4060)
            
            #line 74 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 4041), Tuple.Create<System.Object, System.Int32>(entity.Description
            
            #line default
            #line hidden
, 4041), false)
);

WriteLiteral(">");

            
            #line 74 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                           Write(entity.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 75 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 75 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                 if (appid == 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td>");

            
            #line 77 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                   Write(entity.AppName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 78 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center\"");

WriteAttribute("title", Tuple.Create(" title=\"", 4245), Tuple.Create("\"", 4282)
            
            #line 79 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 4253), Tuple.Create<System.Object, System.Int32>(entity.Mode.GetDescription()
            
            #line default
            #line hidden
, 4253), false)
);

WriteLiteral(">\r\n");

            
            #line 80 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 80 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                     if (entity.Mode == JobModes.Alarm)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <b>");

            
            #line 82 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                      Write(st);

            
            #line default
            #line hidden
WriteLiteral("</b>\r\n");

            
            #line 83 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                    }
                    else
                    {
                        
            
            #line default
            #line hidden
            
            #line 86 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                   Write(st);

            
            #line default
            #line hidden
            
            #line 86 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                           
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 89 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                   Write(entity.End.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n");

            
            #line 91 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 91 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                     if (entity.Mode != JobModes.Message)
                    {
                        if (entity.StepRate > 0)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <span");

WriteLiteral(" style=\"color:lightseagreen\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 96 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                           Write(TimeSpan.FromSeconds(entity.Step));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </span>\r\n");

            
            #line 98 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 101 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                       Write(TimeSpan.FromSeconds(entity.Step));

            
            #line default
            #line hidden
            
            #line 101 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                                              
                        }

                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 106 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                  Write(entity.BatchSize.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n");

            
            #line 108 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 108 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                     if (entity.Mode != JobModes.Message)
                    {
                        
            
            #line default
            #line hidden
            
            #line 110 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                   Write(TimeSpan.FromSeconds(entity.Offset));

            
            #line default
            #line hidden
            
            #line 110 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                                            
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 113 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                  Write(entity.MaxTask.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 114 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                  Write(entity.Total.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 115 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                  Write(entity.Success.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteAttribute("title", Tuple.Create(" title=\"", 5789), Tuple.Create("\"", 5813)
            
            #line 116 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 5797), Tuple.Create<System.Object, System.Int32>(entity.MaxError
            
            #line default
            #line hidden
, 5797), false)
);

WriteLiteral(">");

            
            #line 116 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                                           Write(entity.Error.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 117 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                  Write(entity.Times.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 118 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                  Write(entity.Speed.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6062), Tuple.Create("\"", 6126)
, Tuple.Create(Tuple.Create("", 6069), Tuple.Create("Job/Set/", 6069), true)
            
            #line 120 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 6077), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 6077), false)
, Tuple.Create(Tuple.Create("", 6087), Tuple.Create("?enable=", 6087), true)
            
            #line 120 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 6095), Tuple.Create<System.Object, System.Int32>(entity.Enable?"false":"true"
            
            #line default
            #line hidden
, 6095), false)
);

WriteLiteral(" data-action=\"action\"");

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 6151), Tuple.Create("\"", 6213)
, Tuple.Create(Tuple.Create("", 6159), Tuple.Create("glyphicon", 6159), true)
, Tuple.Create(Tuple.Create(" ", 6168), Tuple.Create("glyphicon-", 6169), true)
            
            #line 120 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                                            , Tuple.Create(Tuple.Create("", 6179), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "ok" : "remove"
            
            #line default
            #line hidden
, 6179), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 6214), Tuple.Create("\"", 6264)
, Tuple.Create(Tuple.Create("", 6222), Tuple.Create("color:", 6222), true)
            
            #line 120 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                                                                                             , Tuple.Create(Tuple.Create(" ", 6228), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "green" : "red"
            
            #line default
            #line hidden
, 6229), false)
, Tuple.Create(Tuple.Create("", 6263), Tuple.Create(";", 6263), true)
);

WriteLiteral("></i></a>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 122 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                                   Write(ut);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6391), Tuple.Create("\"", 6425)
, Tuple.Create(Tuple.Create("", 6398), Tuple.Create("AppMessage?JobID=", 6398), true)
            
            #line 123 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 6415), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 6415), false)
);

WriteLiteral(">消息</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6482), Tuple.Create("\"", 6513)
, Tuple.Create(Tuple.Create("", 6489), Tuple.Create("JobTask?JobID=", 6489), true)
            
            #line 124 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 6503), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 6503), false)
);

WriteLiteral(">任务</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6570), Tuple.Create("\"", 6601)
, Tuple.Create(Tuple.Create("", 6577), Tuple.Create("JobStat?JobID=", 6577), true)
            
            #line 125 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 6591), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 6591), false)
);

WriteLiteral(">统计</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6658), Tuple.Create("\"", 6690)
, Tuple.Create(Tuple.Create("", 6665), Tuple.Create("JobError?JobID=", 6665), true)
            
            #line 126 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 6680), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 6680), false)
);

WriteLiteral(">错误</a></td>\r\n");

            
            #line 127 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 127 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 130 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 132 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 134 "..\..\Areas\Ant\Views\Job\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
