#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 6 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 8 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
    using AntJob;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
    using AntJob.Data;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
    using AntJob.Data.Entity;
    
    #line default
    #line hidden
    using AntJob.Web;
    
    #line 2 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Ant/Views/JobTask/_List_Data.cshtml")]
    public partial class _Areas_Ant_Views_JobTask__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<AntJob.Data.Entity.JobTask>>
    {
        public _Areas_Ant_Views_JobTask__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as List<FieldItem>;
    var fk = fact.Unique;
    var enableSelect = this.EnableSelect();

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 20 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
             if (enableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 23 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 792), Tuple.Create("\"", 831)
            
            #line 24 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 799), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 799), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 884), Tuple.Create("\"", 927)
            
            #line 25 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 891), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("TaskID"))
            
            #line default
            #line hidden
, 891), false)
);

WriteLiteral(">任务</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 980), Tuple.Create("\"", 1022)
            
            #line 26 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 987), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Start"))
            
            #line default
            #line hidden
, 987), false)
);

WriteLiteral(">开始</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1075), Tuple.Create("\"", 1118)
            
            #line 27 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1082), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Client"))
            
            #line default
            #line hidden
, 1082), false)
);

WriteLiteral(">客户端</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1172), Tuple.Create("\"", 1213)
            
            #line 28 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1179), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Step"))
            
            #line default
            #line hidden
, 1179), false)
);

WriteLiteral(">步进</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1266), Tuple.Create("\"", 1312)
            
            #line 29 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1273), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("BatchSize"))
            
            #line default
            #line hidden
, 1273), false)
);

WriteLiteral(">批大小</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1366), Tuple.Create("\"", 1408)
            
            #line 30 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1373), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Total"))
            
            #line default
            #line hidden
, 1373), false)
);

WriteLiteral(">总数</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1461), Tuple.Create("\"", 1505)
            
            #line 31 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1468), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Success"))
            
            #line default
            #line hidden
, 1468), false)
);

WriteLiteral(">成功</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1558), Tuple.Create("\"", 1600)
            
            #line 32 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1565), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Error"))
            
            #line default
            #line hidden
, 1565), false)
);

WriteLiteral(">错误</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1653), Tuple.Create("\"", 1695)
            
            #line 33 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1660), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Times"))
            
            #line default
            #line hidden
, 1660), false)
);

WriteLiteral(">次数</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1748), Tuple.Create("\"", 1790)
            
            #line 34 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1755), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Speed"))
            
            #line default
            #line hidden
, 1755), false)
);

WriteLiteral(">速度</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1843), Tuple.Create("\"", 1884)
            
            #line 35 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1850), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Cost"))
            
            #line default
            #line hidden
, 1850), false)
);

WriteLiteral(">耗时</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1937), Tuple.Create("\"", 1982)
            
            #line 36 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1944), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("FullCost"))
            
            #line default
            #line hidden
, 1944), false)
);

WriteLiteral(">全耗时</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2036), Tuple.Create("\"", 2079)
            
            #line 37 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2043), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Status"))
            
            #line default
            #line hidden
, 2043), false)
);

WriteLiteral(">状态</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2132), Tuple.Create("\"", 2172)
            
            #line 38 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2139), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Key"))
            
            #line default
            #line hidden
, 2139), false)
);

WriteLiteral(">最后键</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2251), Tuple.Create("\"", 2298)
            
            #line 39 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2258), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateTime"))
            
            #line default
            #line hidden
, 2258), false)
);

WriteLiteral(">更新时间</a></th>\r\n");

            
            #line 40 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 40 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 43 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 47 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
         foreach (var entity in Model)
        {
            var cls = "";
            switch (entity.Status)
            {
                case JobStatus.就绪:
                    break;
                case JobStatus.抽取中:
                    cls = "warning";
                    break;
                case JobStatus.处理中:
                    cls = "info";
                    break;
                case JobStatus.错误:
                    cls = "danger";
                    break;
                case JobStatus.完成:
                    cls = "success";
                    break;
                case JobStatus.取消:
                    cls = "active";
                    break;
                default:
                    break;
            }

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 73 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 73 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                 if (enableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3456), Tuple.Create("\"", 3480)
            
            #line 75 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 3464), Tuple.Create<System.Object, System.Int32>(entity[fk.Name]
            
            #line default
            #line hidden
, 3464), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 76 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral(">");

            
            #line 77 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                                                 Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3639), Tuple.Create("\"", 3666)
, Tuple.Create(Tuple.Create("", 3646), Tuple.Create("Job?ID=", 3646), true)
            
            #line 78 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3653), Tuple.Create<System.Object, System.Int32>(entity.JobID
            
            #line default
            #line hidden
, 3653), false)
);

WriteLiteral(">");

            
            #line 78 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                                                  Write(entity.JobName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td>");

            
            #line 79 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
               Write(entity.Start.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 80 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
               Write(entity.Client);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 81 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                  Write(entity.Step.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 82 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                  Write(entity.BatchSize.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 83 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                  Write(entity.Total.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(" style=\"color:forestgreen\"");

WriteLiteral("><b>");

            
            #line 84 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                                               Write(entity.Success.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(">");

            
            #line 85 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                                    Write(entity.Error.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 86 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                  Write(entity.Times.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 87 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                  Write(entity.Speed.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 88 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                  Write(TimeSpan.FromSeconds(entity.Cost));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 89 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                  Write(TimeSpan.FromSeconds(entity.FullCost));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteAttribute("class", Tuple.Create(" class=\"", 4549), Tuple.Create("\"", 4573)
, Tuple.Create(Tuple.Create("", 4557), Tuple.Create("text-center", 4557), true)
            
            #line 90 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
, Tuple.Create(Tuple.Create(" ", 4568), Tuple.Create<System.Object, System.Int32>(cls
            
            #line default
            #line hidden
, 4569), false)
);

WriteLiteral(">");

            
            #line 90 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                                        Write(entity.Status);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 91 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
               Write(entity.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 92 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
               Write(entity.UpdateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 93 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 93 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 96 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 98 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 100 "..\..\Areas\Ant\Views\JobTask\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
