#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Ant\Views\App\_List_Search.cshtml"
    using AntJob.Data.Entity;
    
    #line default
    #line hidden
    using AntJob.Web;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Ant/Views/App/_List_Search.cshtml")]
    public partial class _Areas_Ant_Views_App__List_Search_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Ant_Views_App__List_Search_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Ant\Views\App\_List_Search.cshtml"
  
    var page = ViewBag.Page as Pager;
    var dic = new Dictionary<Int32, String>();
    dic.Add(1, "启用");
    dic.Add(0, "禁用");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"enable\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">状态：</label>\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Areas\Ant\Views\App\_List_Search.cshtml"
Write(Html.ForDropDownList("enable", dic, Request["enable"], "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <label");

WriteLiteral(" for=\"category\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">分类：</label>\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Areas\Ant\Views\App\_List_Search.cshtml"
Write(Html.ForDropDownList("category", AntJob.Data.Entity.App.FindAllCategoryByCache(), Request["category"], "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
