#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AntJob.Web;
    
    #line 2 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Ant/Views/App/_List_Data.cshtml")]
    public partial class _Areas_Ant_Views_App__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<AntJob.Data.Entity.App>>
    {
        public _Areas_Ant_Views_App__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var enableSelect = this.EnableSelect();
    var provider = ManageProvider.Provider;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 20 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
             if (enableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 23 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 823), Tuple.Create("\"", 862)
            
            #line 24 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 830), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 830), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 915), Tuple.Create("\"", 956)
            
            #line 25 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 922), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Name"))
            
            #line default
            #line hidden
, 922), false)
);

WriteLiteral(">名称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1009), Tuple.Create("\"", 1057)
            
            #line 26 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1016), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("DisplayName"))
            
            #line default
            #line hidden
, 1016), false)
);

WriteLiteral(">显示名</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1111), Tuple.Create("\"", 1160)
            
            #line 27 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1118), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("MessageCount"))
            
            #line default
            #line hidden
, 1118), false)
);

WriteLiteral(">消息数</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1214), Tuple.Create("\"", 1259)
            
            #line 28 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1221), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("JobCount"))
            
            #line default
            #line hidden
, 1221), false)
);

WriteLiteral(">作业数</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1313), Tuple.Create("\"", 1356)
            
            #line 29 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1320), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Enable"))
            
            #line default
            #line hidden
, 1320), false)
);

WriteLiteral(">启用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">消息</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">在线</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">任务</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">错误</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1614), Tuple.Create("\"", 1661)
            
            #line 34 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1621), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateTime"))
            
            #line default
            #line hidden
, 1621), false)
);

WriteLiteral(">更新时间</a></th>\r\n");

            
            #line 35 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:100px;\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 38 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 42 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 42 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
         foreach (var entity in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 45 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                 if (enableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2126), Tuple.Create("\"", 2144)
            
            #line 47 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 2134), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2134), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 48 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral(">");

            
            #line 49 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                                                                 Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2303), Tuple.Create("\"", 2358)
            
            #line 50 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2310), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Job",new {appid=entity.ID})
            
            #line default
            #line hidden
, 2310), false)
);

WriteLiteral(">");

            
            #line 50 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                                                                                              Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td>");

            
            #line 51 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
               Write(entity.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 52 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
               Write(entity.MessageCount.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2533), Tuple.Create("\"", 2588)
            
            #line 53 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2540), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Job",new {appid=entity.ID})
            
            #line default
            #line hidden
, 2540), false)
);

WriteLiteral(">");

            
            #line 53 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                                                                                              Write(entity.JobCount);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2681), Tuple.Create("\"", 2745)
, Tuple.Create(Tuple.Create("", 2688), Tuple.Create("App/Set/", 2688), true)
            
            #line 55 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2696), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2696), false)
, Tuple.Create(Tuple.Create("", 2706), Tuple.Create("?enable=", 2706), true)
            
            #line 55 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2714), Tuple.Create<System.Object, System.Int32>(entity.Enable?"false":"true"
            
            #line default
            #line hidden
, 2714), false)
);

WriteLiteral(" data-action=\"action\"");

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 2770), Tuple.Create("\"", 2832)
, Tuple.Create(Tuple.Create("", 2778), Tuple.Create("glyphicon", 2778), true)
, Tuple.Create(Tuple.Create(" ", 2787), Tuple.Create("glyphicon-", 2788), true)
            
            #line 55 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                                                            , Tuple.Create(Tuple.Create("", 2798), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "ok" : "remove"
            
            #line default
            #line hidden
, 2798), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 2833), Tuple.Create("\"", 2883)
, Tuple.Create(Tuple.Create("", 2841), Tuple.Create("color:", 2841), true)
            
            #line 55 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                                                                                                             , Tuple.Create(Tuple.Create(" ", 2847), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "green" : "red"
            
            #line default
            #line hidden
, 2848), false)
, Tuple.Create(Tuple.Create("", 2882), Tuple.Create(";", 2882), true)
);

WriteLiteral("></i></a>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2960), Tuple.Create("\"", 3022)
            
            #line 57 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2967), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","AppMessage",new {appid=entity.ID})
            
            #line default
            #line hidden
, 2967), false)
);

WriteLiteral(">消息</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3079), Tuple.Create("\"", 3140)
            
            #line 58 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3086), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","AppOnline",new {appid=entity.ID})
            
            #line default
            #line hidden
, 3086), false)
);

WriteLiteral(">在线</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3197), Tuple.Create("\"", 3256)
            
            #line 59 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3204), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","JobTask",new {appid=entity.ID})
            
            #line default
            #line hidden
, 3204), false)
);

WriteLiteral(">任务</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3313), Tuple.Create("\"", 3373)
            
            #line 60 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3320), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","JobError",new {appid=entity.ID})
            
            #line default
            #line hidden
, 3320), false)
);

WriteLiteral(">错误</a></td>\r\n                <td>");

            
            #line 61 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
               Write(entity.UpdateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 62 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 62 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 65 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 67 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 69 "..\..\Areas\Ant\Views\App\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
