#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AntJob.Web;
    
    #line 2 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Ant/Views/JobError/_List_Data.cshtml")]
    public partial class _Areas_Ant_Views_JobError__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<AntJob.Data.Entity.JobError>>
    {
        public _Areas_Ant_Views_JobError__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as List<FieldItem>;

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n\r\n    .OverFlow {\r\n        overflow: hidden;\r\n        text-overflow: e" +
"llipsis;\r\n        white-space: nowrap;\r\n        max-width: 400px;\r\n    }\r\n</styl" +
"e>\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 723), Tuple.Create("\"", 762)
            
            #line 27 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 730), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 730), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 815), Tuple.Create("\"", 857)
            
            #line 28 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 822), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("AppID"))
            
            #line default
            #line hidden
, 822), false)
);

WriteLiteral(">应用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 935), Tuple.Create("\"", 982)
            
            #line 29 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 942), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("TaskItemID"))
            
            #line default
            #line hidden
, 942), false)
);

WriteLiteral(">任务项</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1036), Tuple.Create("\"", 1077)
            
            #line 30 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1043), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Step"))
            
            #line default
            #line hidden
, 1043), false)
);

WriteLiteral(">步进</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1130), Tuple.Create("\"", 1176)
            
            #line 31 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1137), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("BatchSize"))
            
            #line default
            #line hidden
, 1137), false)
);

WriteLiteral(">批大小</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1230), Tuple.Create("\"", 1270)
            
            #line 32 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1237), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Key"))
            
            #line default
            #line hidden
, 1237), false)
);

WriteLiteral(">数据键</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1324), Tuple.Create("\"", 1370)
            
            #line 33 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1331), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ErrorCode"))
            
            #line default
            #line hidden
, 1331), false)
);

WriteLiteral(">错误码</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">内容</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1494), Tuple.Create("\"", 1541)
            
            #line 35 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1501), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateTime"))
            
            #line default
            #line hidden
, 1501), false)
);

WriteLiteral(">更新时间</a></th>\r\n");

            
            #line 36 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 36 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:100px;\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 39 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 43 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
         foreach (var entity in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral(">");

            
            #line 46 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
                                                                 Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1982), Tuple.Create("\"", 2012)
, Tuple.Create(Tuple.Create("", 1989), Tuple.Create("Job?AppID=", 1989), true)
            
            #line 47 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1999), Tuple.Create<System.Object, System.Int32>(entity.AppID
            
            #line default
            #line hidden
, 1999), false)
);

WriteLiteral(">");

            
            #line 47 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
                                                 Write(entity.AppName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2062), Tuple.Create("\"", 2096)
, Tuple.Create(Tuple.Create("", 2069), Tuple.Create("JobTask?JobID=", 2069), true)
            
            #line 48 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2083), Tuple.Create<System.Object, System.Int32>(entity.JobID
            
            #line default
            #line hidden
, 2083), false)
);

WriteLiteral(">");

            
            #line 48 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
                                                     Write(entity.JobName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 49 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
                                  Write(entity.Step.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 50 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
                                  Write(entity.BatchSize.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 51 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
               Write(entity.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 52 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
               Write(entity.ErrorCode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"OverFlow\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2393), Tuple.Create("\"", 2416)
            
            #line 53 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2401), Tuple.Create<System.Object, System.Int32>(entity.Message
            
            #line default
            #line hidden
, 2401), false)
);

WriteLiteral(">");

            
            #line 53 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
                                                        Write(entity.Message);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 54 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
               Write(entity.UpdateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 55 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 55 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 58 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 60 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 62 "..\..\Areas\Ant\Views\JobError\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
