#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AntJob.Web;
    
    #line 2 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Ant/Views/AppMessage/_List_Data.cshtml")]
    public partial class _Areas_Ant_Views_AppMessage__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<AntJob.Data.Entity.AppMessage>>
    {
        public _Areas_Ant_Views_AppMessage__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var enableSelect = this.EnableSelect();
    //var provider = ManageProvider.Provider;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 20 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
             if (enableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 23 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 832), Tuple.Create("\"", 871)
            
            #line 24 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 839), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 839), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 924), Tuple.Create("\"", 966)
            
            #line 25 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 931), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("AppID"))
            
            #line default
            #line hidden
, 931), false)
);

WriteLiteral(">应用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1019), Tuple.Create("\"", 1061)
            
            #line 26 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1026), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("JobID"))
            
            #line default
            #line hidden
, 1026), false)
);

WriteLiteral(">作业</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"主题。区分作业下多种资源\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1135), Tuple.Create("\"", 1177)
            
            #line 27 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1142), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Topic"))
            
            #line default
            #line hidden
, 1142), false)
);

WriteLiteral(">主题</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1255), Tuple.Create("\"", 1302)
            
            #line 28 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1262), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("CreateTime"))
            
            #line default
            #line hidden
, 1262), false)
);

WriteLiteral(">创建时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1382), Tuple.Create("\"", 1429)
            
            #line 29 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1389), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateTime"))
            
            #line default
            #line hidden
, 1389), false)
);

WriteLiteral(">更新时间</a></th>\r\n");

            
            #line 30 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:100px;\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 33 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 37 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
         foreach (var entity in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 40 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 40 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
                 if (enableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1894), Tuple.Create("\"", 1912)
            
            #line 42 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 1902), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 1902), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 43 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral(">");

            
            #line 44 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
                                                                 Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2051), Tuple.Create("\"", 2078)
, Tuple.Create(Tuple.Create("", 2058), Tuple.Create("App?ID=", 2058), true)
            
            #line 45 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2065), Tuple.Create<System.Object, System.Int32>(entity.AppID
            
            #line default
            #line hidden
, 2065), false)
);

WriteLiteral(">");

            
            #line 45 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
                                              Write(entity.AppName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2128), Tuple.Create("\"", 2155)
, Tuple.Create(Tuple.Create("", 2135), Tuple.Create("Job?ID=", 2135), true)
            
            #line 46 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2142), Tuple.Create<System.Object, System.Int32>(entity.JobID
            
            #line default
            #line hidden
, 2142), false)
);

WriteLiteral(">");

            
            #line 46 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
                                              Write(entity.JobName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td>");

            
            #line 47 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
               Write(entity.Topic);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 48 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
               Write(entity.CreateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 49 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
               Write(entity.UpdateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 50 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 50 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 53 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 55 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 57 "..\..\Areas\Ant\Views\AppMessage\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
