#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AntJob.Web;
    
    #line 2 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Ant/Views/AppOnline/_List_Data.cshtml")]
    public partial class _Areas_Ant_Views_AppOnline__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<AntJob.Data.Entity.AppOnline>>
    {
        public _Areas_Ant_Views_AppOnline__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var enableSelect = this.EnableSelect();
    //var provider = ManageProvider.Provider;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 20 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
             if (enableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 23 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 831), Tuple.Create("\"", 870)
            
            #line 24 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 838), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 838), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 923), Tuple.Create("\"", 965)
            
            #line 25 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 930), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("AppID"))
            
            #line default
            #line hidden
, 930), false)
);

WriteLiteral(">应用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"客户端。IP加进程\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1036), Tuple.Create("\"", 1079)
            
            #line 26 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1043), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Client"))
            
            #line default
            #line hidden
, 1043), false)
);

WriteLiteral(">客户端</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1133), Tuple.Create("\"", 1177)
            
            #line 27 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1140), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Version"))
            
            #line default
            #line hidden
, 1140), false)
);

WriteLiteral(">版本</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1230), Tuple.Create("\"", 1273)
            
            #line 28 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1237), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Server"))
            
            #line default
            #line hidden
, 1237), false)
);

WriteLiteral(">服务端</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1327), Tuple.Create("\"", 1369)
            
            #line 29 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1334), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Tasks"))
            
            #line default
            #line hidden
, 1334), false)
);

WriteLiteral(">任务数</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1423), Tuple.Create("\"", 1465)
            
            #line 30 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1430), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Total"))
            
            #line default
            #line hidden
, 1430), false)
);

WriteLiteral(">总数</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1518), Tuple.Create("\"", 1562)
            
            #line 31 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1525), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Success"))
            
            #line default
            #line hidden
, 1525), false)
);

WriteLiteral(">成功</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1615), Tuple.Create("\"", 1657)
            
            #line 32 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1622), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Error"))
            
            #line default
            #line hidden
, 1622), false)
);

WriteLiteral(">错误</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"耗时。总耗时，秒\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1727), Tuple.Create("\"", 1768)
            
            #line 33 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1734), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Cost"))
            
            #line default
            #line hidden
, 1734), false)
);

WriteLiteral(">耗时</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"速度。每秒处理数\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1838), Tuple.Create("\"", 1880)
            
            #line 34 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1845), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Speed"))
            
            #line default
            #line hidden
, 1845), false)
);

WriteLiteral(">速度</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1958), Tuple.Create("\"", 2005)
            
            #line 35 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1965), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("CreateTime"))
            
            #line default
            #line hidden
, 1965), false)
);

WriteLiteral(">创建时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2085), Tuple.Create("\"", 2132)
            
            #line 36 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2092), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateTime"))
            
            #line default
            #line hidden
, 2092), false)
);

WriteLiteral(">更新时间</a></th>\r\n");

            
            #line 37 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:100px;\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 40 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 44 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
         foreach (var entity in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 47 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                 if (enableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2597), Tuple.Create("\"", 2615)
            
            #line 49 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 2605), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2605), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 50 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral(">");

            
            #line 51 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                                                                 Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2754), Tuple.Create("\"", 2781)
, Tuple.Create(Tuple.Create("", 2761), Tuple.Create("App?ID=", 2761), true)
            
            #line 52 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2768), Tuple.Create<System.Object, System.Int32>(entity.AppID
            
            #line default
            #line hidden
, 2768), false)
);

WriteLiteral(">");

            
            #line 52 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                                              Write(entity.AppName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 2828), Tuple.Create("\"", 2848)
            
            #line 53 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2836), Tuple.Create<System.Object, System.Int32>(entity.Name
            
            #line default
            #line hidden
, 2836), false)
);

WriteLiteral(">");

            
            #line 53 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                                    Write(entity.Client);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 54 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
               Write(entity.Version);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 55 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
               Write(entity.Server);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2995), Tuple.Create("\"", 3078)
            
            #line 56 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3002), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","JobTask",new {appid=entity.AppID,client=entity.Client})
            
            #line default
            #line hidden
, 3002), false)
);

WriteLiteral(">");

            
            #line 56 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                                                                                                                         Write(entity.Tasks.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 57 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                                  Write(entity.Total.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 58 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                                  Write(entity.Success.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3310), Tuple.Create("\"", 3394)
            
            #line 59 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3317), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","JobError",new {appid=entity.AppID,client=entity.Client})
            
            #line default
            #line hidden
, 3317), false)
);

WriteLiteral(">");

            
            #line 59 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                                                                                                                          Write(entity.Error.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 60 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                                  Write(TimeSpan.FromSeconds(entity.Cost));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 61 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                                  Write(entity.Speed.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 62 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
               Write(entity.CreateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 63 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
               Write(entity.UpdateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 64 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 64 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 67 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 69 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 71 "..\..\Areas\Ant\Views\AppOnline\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
